name = "cf-worker-ws-dev21"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "c5162e1f-ab63-45c6-bafe-f26cdc6840a6"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
